config/routes.rb
Rails.application.routes.draw do

  devise_for :users
    as :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :tasks

  resources :boards do
    resources :projects
  end

  get 'trello_import/new_board_import'
  post 'trello_import/create_board_import'

  root 'boards#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    # can :read, :all # permissions for every user, even if not logged in


    if user.present?  # additional permissions for logged in users (they can manage their posts)
      # can :manage, Board, Column, Card, Task, Project, user_id: user.id
      can :manage, :all
      # if user.admin?  # additional permissions for administrators
      #   can :manage, :all
      # end
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  def self.types
    %w(Image Video)
  end
end

app/models/board.rb
class Board < ApplicationRecord
  after_create :check_type_and_create_columns

  belongs_to :project, optional: true
  belongs_to :user

  has_many :columns

  def check_type_and_create_columns
    create_general_columns if name == 'General'
    create_inbox_and_done if general == true
    create_priority_columns if name == 'Priorities'
  end

  def create_general_columns
    columns = ['In Progress', 'Priority', 'To Do', 'Waiting', 'Someday']
    create_columns(columns)
  end

  def create_inbox_and_done
    columns = ['Done', 'Inbox']
    create_columns(columns)
  end

  def create_priority_columns
    columns = ['High', 'Middle', 'Low', 'None']
    create_columns(columns)
  end

  def create_columns(columns)
    columns.each_with_index do |c, i|
      self.columns.create(name: c, position: i)
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  # after_create :attach_to_user

  belongs_to :user

  # def attach_to_user
    # self.user_id = User.current.id
  # end
end

app/models/card_in_column.rb
class CardInColumn < ApplicationRecord
  belongs_to :column
  belongs_to :columnable, polymorphic: true
end

app/models/column.rb
class Column < ApplicationRecord
  has_many :card_in_columns
  has_many :tasks,    through: :card_in_columns, source: :columnable, source_type: 'Task'
  has_many :projects, through: :card_in_columns, source: :columnable, source_type: 'Project'
  belongs_to :board
end

app/models/image.rb
class Image < Attachment
  mount_uploader :image, ImageUploader
end

app/models/link.rb
class Link < Attachment
end

app/models/project.rb
class Project < Card
  has_many :tasks
  
  has_many :card_in_columns, as: :columnable
  has_many :columns, through: :card_in_columns
end

app/models/task.rb
class Task < Card
  belongs_to :project, optional: true

  has_many :card_in_columns, as: :columnable
  has_many :columns, through: :card_in_columns
end

app/models/trello_import.rb
class TrelloImport < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :create_general_board, :create_priorities_board

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards
  has_many :tasks
  has_many :projects
  has_many :trello_imports

  def create_general_board
    board = self.boards.create(name: 'General', general: true)
    board.save!
  end

  def create_priorities_board
    board = self.boards.create(name: 'Priorities')
    board.save!
  end
end

app/controllers/react/tasks_controller.rb
class React::TasksController < ApplicationController
  # before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def index
    @user = current_user
    @are_tasks = true

    if user_signed_in?
      @boards = @user.boards.as_json(include: { columns: {
                                                include: { cards: {
                                                           only: [:id, :name, :description, :project_id, :type],
                                                           include: { card_in_columns: {
                                                                      include: { card: {
                                                                                 only: [:id, :name, :description, :project_id, :type],
                                                                      } }
                                                           } }
                                                         }}
      } })
    end
  end

  def show
    @board = Board.find_by(general: true)
    @columns = @board.columns

    @columns.each do |column|
      @cards = column.cards
      @tasks = @cards.where("type = 'Task'")
      @projects = @cards.where("type = 'Project'")
      @card_in_columns = column.card_in_columns
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @projects = Project.all
    @columns = Column.all
  end

  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @columns = Column.all
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    @user = current_user
    @task.user_id = @user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:project_id, :name, :description, :user_id, card_in_columns_attributes: [:id, :column_id, :card_id])
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= select("task", "project_id", Project.all.collect { |a| [a.name, a.id] }, { include_blank: true }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="O_Card Task">
  <%= link_to task.name, task_path(task), remote: true %>
</div>

app/views/tasks/_task_popup.html.erb
<div class="taskPopup">
  <div class="close">X</div>
  <h1><%= @task.name %></h1>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>
<% @tasks.each do |task| %>
  <%= task.name %>
  <% @projects.each do |project| %>
    <% if project.id = task.project_id %>
      <p>project: <strong><%= project.name %></strong></p>
    <% end %>
  <% end %>
  <%= link_to 'Show', task %>
  <%= link_to 'Edit', edit_task_path(task) %>
  <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %> <br><br><br>
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @task.name %></h1>
<%= @task.description %> <br>
<% if @task.project_id %>
  <p>in project <strong><%= @project.name %></strong></p>
<% end %>
<br><br>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/show.js.erb
$('body').append('<%= j render "tasks/task_popup" %>')
$('.close').on('click', function() {
  $(this).parent().remove()
})