config/routes.rb
Rails.application.routes.draw do

  devise_for :users
    as :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :tasks

  resources :boards do
    resources :projects
  end

  get 'trello_import/new_board_import'
  post 'trello_import/create_board_import'

  root 'boards#index'
end

app/models/project.rb
class Project < Card
  has_many :tasks
  
  has_many :card_in_columns, as: :columnable
  has_many :columns, through: :card_in_columns
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  before_action :set_general_board, :set_boards, only: [:index, :show]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @general_board = current_user.boards.find_by_name('General')
    @board = current_user.boards.find(params[:board_id])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @board = current_user.boards.find(params[:board_id])
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :type, :user_id, card_in_columns_attributes: [:id, :column_id, :card_id])
    end
end

app/controllers/react/projects_controller.rb
class React::ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @user = current_user

    if user_signed_in?
      @boards = @user.boards.as_json(include: { columns: {
                                                include: { cards: {
                                                           only: [:id, :name, :description, :project_id, :type],
                                                           include: { card_in_columns: {
                                                                      include: { card: {
                                                                                 only: [:id, :name, :description, :project_id, :type],
                                                                      } }
                                                           } }
                                                         }}
      } })
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @user = current_user

    if user_signed_in?
      @project.as_json
      @boards = Board.all.as_json(include: { columns: {
                                                include: { cards: {
                                                           only: [:id, :name, :description, :project_id, :type],
                                                           include: { card_in_columns: {
                                                                      include: { card: {
                                                                                 only: [:id, :name, :description, :project_id, :type],
                                                                      } }
                                                           } }
                                                         }}
      } })
    end
  end

  # GET /projects/new
  def new
    @user = current_user
    @project = Project.new

    if user_signed_in?
      @boards = @user.boards.as_json(include: { columns: {
                                                include: { cards: {
                                                           only: [:id, :name, :description, :project_id, :type], include: :card_in_columns
                                                         }}
      } })
    end
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :type, card_in_columns_attributes: [:id, :column_id, :card_id])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>name</p>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <p>description</p>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="O_Card Project">
  <%= link_to project.name, board_project_path(@board, project) %>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% content_for :boards_menu do %>
  <menu class="O_Menubar">
    <div class="left">
      <% @boards.each do |board| %>
        <%= link_to board.name, board_projects_path(board) %>
      <% end %>
    </div>

    <div class="right"></div>
  </menu>
<% end %>

<%= render partial: 'columns/projects_column', collection: @board.columns %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<div id="newBoardInProject">
  <%= link_to 'Add board', action: :new_board_in_project, controller: :board_in_projects, remote: true %>
</div>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<% content_for :boards_menu do %>
  <menu class="O_Menubar">
    <div class="left">
      <% @boards.each do |board| %>
        <%= link_to board.name, board_project_path(board, @project) %>
      <% end %>
    </div>

    <div class="right"></div>
  </menu>
<% end %>

<%= render partial: 'columns/project_column', collection: @board.columns %>