config/routes.rb
Rails.application.routes.draw do

  devise_for :users
    as :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :tasks

  resources :boards do
    resources :projects
  end

  get 'trello_import/new_board_import'
  post 'trello_import/create_board_import'

  root 'boards#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    # can :read, :all # permissions for every user, even if not logged in


    if user.present?  # additional permissions for logged in users (they can manage their posts)
      # can :manage, Board, Column, Card, Task, Project, user_id: user.id
      can :manage, :all
      # if user.admin?  # additional permissions for administrators
      #   can :manage, :all
      # end
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  def self.types
    %w(Image Video)
  end
end

app/models/board.rb
class Board < ApplicationRecord
  after_create :check_type_and_create_columns

  belongs_to :project, optional: true
  belongs_to :user

  has_many :columns

  def check_type_and_create_columns
    create_general_columns if name == 'General'
    create_inbox_and_done if general == true
    create_priority_columns if name == 'Priorities'
  end

  def create_general_columns
    columns = ['In Progress', 'Priority', 'To Do', 'Waiting', 'Someday']
    create_columns(columns)
  end

  def create_inbox_and_done
    columns = ['Done', 'Inbox']
    create_columns(columns)
  end

  def create_priority_columns
    columns = ['High', 'Middle', 'Low', 'None']
    create_columns(columns)
  end

  def create_columns(columns)
    columns.each_with_index do |c, i|
      self.columns.create(name: c, position: i)
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  # after_create :attach_to_user

  belongs_to :user

  # def attach_to_user
    # self.user_id = User.current.id
  # end
end

app/models/card_in_column.rb
class CardInColumn < ApplicationRecord
  belongs_to :column
  belongs_to :columnable, polymorphic: true
end

app/models/column.rb
class Column < ApplicationRecord
  has_many :card_in_columns
  has_many :tasks,    through: :card_in_columns, source: :columnable, source_type: 'Task'
  has_many :projects, through: :card_in_columns, source: :columnable, source_type: 'Project'
  belongs_to :board
end

app/models/image.rb
class Image < Attachment
  mount_uploader :image, ImageUploader
end

app/models/link.rb
class Link < Attachment
end

app/models/project.rb
class Project < Card
  has_many :tasks
  
  has_many :card_in_columns, as: :columnable
  has_many :columns, through: :card_in_columns
end

app/models/task.rb
class Task < Card
  belongs_to :project, optional: true

  has_many :card_in_columns, as: :columnable
  has_many :columns, through: :card_in_columns
end

app/models/trello_import.rb
class TrelloImport < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :create_general_board, :create_priorities_board

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards
  has_many :tasks
  has_many :projects
  has_many :trello_imports

  def create_general_board
    board = self.boards.create(name: 'General', general: true)
    board.save!
  end

  def create_priorities_board
    board = self.boards.create(name: 'Priorities')
    board.save!
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Psycho</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= link_to 'Tasks', root_url %>
      <%= link_to 'Projects', board_projects_url(@board) %>
      <hr>
    <% end %>

    <%= yield :boards_menu %>

    <%= yield %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/react.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'app'  %>
  </head>
  <body>
    <%#= react_component("Main",
      props: {
        board: @board,
        columns: @columns,
        cards: @cards,
        cardInColumns: @card_in_columns
      },
      prerender: false)
    %>

    <%= yield %>
  </body>
</html>

app/views/layouts/trello_import.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Psycho</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'menubar' %>

    <section>
      <%= yield %>
    </section>
  </body>
</html>